### ISSUE TITLE
A bit more sample code xbrl to graph

### ISSUE THREAD

**Issue by pdavidsonFIA** [wjwillemse/xbrl2rdf#1]
I'm struggling to get started with this.
This paper is very abstract:
http://events.linkeddata.org/ldow2009/papers/ldow2009_paper6.pdf
In the notebook on xbrl2rdf you're already working on a converted rdf but a quick example of this first step would be a help.

I anticipate using this:

- to look through the published zip taxonomies
- extract information from our published QRTs

It would be super helpful for a snippet or two starting from the template_instance.xbrl that eiopa publish

**Comment by wjwillemse** [comment]
I have updated the README.rst to get the qrs_240_instance.ttl that is used in the notebook. Could you try this? This code could be included in the notebook, but that would take a bit more time.

**Comment by pdavidsonFIA** [comment]
it does something, but doesn't fully run:
![image](https://user-images.githubusercontent.com/57438470/123944932-ec26f100-d99d-11eb-9206-31545f12718f.png)

folders manually created:
/data/instances (contains qrs_240_instance.xbrl)
/data/rdf
/data/taxonomies (contains EIOPA_SolvencyII_XBRL_Taxonomy_2.4.0_hotfix.zip)

I get qrs_240_instance.log in rdf and taxonomyPackages.json in taxonomies being created.

**Comment by wjwillemse** [comment]
You are almost there. The command 'python -m xbrl2rdf.xbrl2rdf' will request the instance, the taxonomy, the output location and the output format. For the instance and the taxonomy it will list the available files with a number. For the taxonomy you entered the default (2) but that one does not exists. In your case you should enter 0 for the taxonomy. I should also fix this...

**Comment by pdavidsonFIA** [comment]
ok, now i progressed to a log error:
![image](https://user-images.githubusercontent.com/57438470/123946905-01048400-d9a0-11eb-9b5b-55bd9e3f41d1.png)

**Comment by pdavidsonFIA** [comment]
ah, so it no produces the ttl
-> but only for EIOPA_SolvencyII_XBRL_Taxonomy_2.4.0_with_external_hotfix.zip
and not
EIOPA_SolvencyII_XBRL_Taxonomy_2.4.0_hotfix.zip

**Comment by pdavidsonFIA** [comment]
And the demo notebok runs now, super - going to explore a bit more. Thanks!
